# Generated by Django 4.2 on 2023-09-05 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_newuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUser',
            new_name='NewUserDetail',
        ),
    ]
